# Generated by Django 4.1.7 on 2023-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('delivery_date', models.DateField()),
                ('rub_price', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
